/* Generated by Nim Compiler v1.2.0 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0) {
	NimStringV2 s;
	int T6_;
	int T7_;
NIM_BOOL* nimErr_;
	nimfr_("echoBinSafe", "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\io.nim");
{nimErr_ = nimErrorFlag();
	s.len = 0; s.p = NIM_NIL;
	nimln_(638, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\io.nim");
	flockfile(stdout);
	{
		NI i;
		nimln_(3, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\iterator"
"s.nim");
		i = ((NI) 0);
		{
			nimln_(4, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\iterator"
"s.nim");
			while (1) {
				int T5_;
				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_2;
				if (!(i < argsLen_0)) goto LA4;
				nimln_(49, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\fatal.ni"
"m");
				if ((NU)(i) >= (NU)(argsLen_0)){ raiseIndexError2(i,argsLen_0-1); goto LA1_;
}
				eq___aBBXmHFBEivKqERloP6zmA_2((&s), args[i]);
				nimln_(645, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\io.nim");
				T5_ = (int)0;
				T5_ = fwrite(((void*) (nimToCStringConv(s))), ((size_t) (s.len)), ((size_t) 1), stdout);
				(void)(T5_);
				nimln_(6, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\iterator"
"s.nim");
				if (nimAddInt(i, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_2)) { raiseOverflow(); goto LA1_;
};
				i = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2);
			} LA4: ;
		}
	}
	nimln_(647, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\io.nim");
	T6_ = (int)0;
	T6_ = fwrite(((void*) ("\012")), ((size_t) 1), ((size_t) 1), stdout);
	(void)(T6_);
	nimln_(648, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\io.nim");
	T7_ = (int)0;
	T7_ = fflush(stdout);
	(void)(T7_);
	nimln_(650, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\io.nim");
	funlockfile(stdout);
	{
		LA1_:;
	}
	{
		nimln_(49, "C:\\Users\\me\\.choosenim\\toolchains\\nim-1.2.0\\lib\\system\\fatal.ni"
"m");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&s));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
